---
- name: Install zip archive utilities
  pacman:
    name:
      - zip
      - unzip
      - p7zip
    state: present
  tags:
    - zip

- name: Install ventoy
  aur:
    name: ventoy-bin
    user: "{{ user.name }}"
  tags:
    - aur
    - ventoy
