---
- name: Configure network adapter
  template: src=20-wired.network.j2 dest=/etc/systemd/network/20-wired.network
    
- name: Enable and start systemd-netword service
  service: name=systemd-networkd enabled=yes state=started
  notify:
    - reload systemd config
  tags:
    - systemd-networkd

- name: Enable and start systemd-resolved service
  service: name=systemd-resolved enabled=yes state=started
  notify:
    - reload systemd config
  tags:
    - systemd-networkd

- name: Enable resolve.conf with systemd
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
