---
- name: Install texlive-core
  pacman:
    name: texlive-core
    state: present

- name: Install texlive-latexextra
  pacman:
    name: texlive-latexextra
    state: present

- name: Install GNU Plot
  pacman:
    name: gnuplot
    state: present

- name: Install xsv
  aur:
    name: xsv
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install pandoc and dependencies
  aur:
    name: pandoc-bin
    user: "{{ user.name }}"
  tags:
    - aur

