---
- name: Install onlykey
  aur: name=onlykey user={{ user.name }}
  tags:
    - aur

- name: Install smartcard libs/tools
  pacman:
    name:
      - pcsclite
      - libusb-compat
      - ccid
    state: present
