---
- name: Install sshfs
  pacman:
    name: sshfs
    state: present

- name: Install autossh
  pacman:
    name: autossh
    state: present

- name: Copy fuse configuration file
  copy:
    src: fuse.conf
    dest: /etc/fuse.conf

- name: Install keychain
  pacman:
    name: keychain
    state: present

- name: Install x11-ask-pass
  pacman:
    name: x11-ssh-askpass
    state: present

- name: Export SSH_ASKPASS environment variable
  lineinfile:
    dest: /etc/profile
    state: present
    line: "export SSH_ASKPASS=\"/usr/lib/ssh/x11-ssh-askpass\""

- name: Make directory for user SSH key
  file:
    path: /home/{{ user.name }}/.ssh
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
