---
- include: beets.yml
- include: imagemagick.yml
- include: teiler.yml
- include: flac2all.yml
- include: qcode.yml

- name: Install misc media codecs and helpers
  pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - perl-image-exiftool
      - perl-archive-zip
      - opus-tools
    state: present

- name: Install youtube-dl
  pacman:
    name: yt-dlp
    state: present

- name: Install zbar
  pacman:
    name: zbar
    state: present
