---
- include_tasks: beets.yml
- include_tasks: imagemagick.yml
- include_tasks: flac2all.yml
- include_tasks: qcode.yml
- include_tasks: imv.yml

- name: Install misc media codecs and helpers
  pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - perl-image-exiftool
      - perl-archive-zip
      - opus-tools
    state: present

- name: Install youtube-dl
  pacman:
    name: yt-dlp
    state: present

- name: Install zbar
  pacman:
    name: zbar
    state: present
