---
- name: Install Bash
  pacman:
    name:
      - bash
      - bash-completion
    state: present
  tags:
    - shell

- name: Install ZSH
  pacman:
    name:
      - zsh
      - zsh-completions
    state: present
  tags:
    - shell

- name: Create ZSH cache dir
  file:
    path: /home/{{ user.name }}/.cache/zsh
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags:
    - shell
